### ISSUE TITLE
Unable to download songs on Android 14

### ISSUE THREAD

**Issue by theinhumaneme** [KRTirtho/spotube#1015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to download songs, it loads for while before throwing the exlamation mark and error, doesn't work when I re-try.

### Expected Behavior

songs should download normally as shown in the project showcase

### Steps to reproduce

1. Open the app.
2. open a playlist
3. select songs and download

### Operating System

Android 14

### Spotube version

3.4.0

### Installation source

GitHub Releases (Binary)

### Additional information

I looked into permissions, the only permissions the app has access music from the filesystem, no other permissions are being asked. 

I can't fetch the logs as well from the app it is empty, i think it is because the app is not able to write to the file system atleast this is what i am assuming, i am no android dev, please let me know if there is any i can help you with obtaining the logs :D

**Comment by nottisa** [comment]
Having a similar issue. Spotube version: 3.4.0 
Pixel 6 pro - raven - UQ1A.231205.015

Log attached

- Log seems to load slowly
- Seems to be a permission issue
- When I updated the app I didn't have a custom download folder set, once I set one, it started erroring.

**Comment by KRTirtho** [comment]
Fixed it. It'll be available in the next release.
Or, try out the nightly release of tomorrow

**Comment by xard** [comment]
doesn't download any track...

v3.7.1
nightly
build 318

install in trollstore
iOS (.ipa)

**Comment by Abhi-gautam96** [comment]
Version: v3.8.3
Channel: stable
Build Number: 37

Still not able to download songs

**Comment by Ok2dot0** [comment]
Still same problem.
Android 10
Samsung Galaxy A6
App Version 3.9.0
Any music source is not working, but playback works
