### ISSUE TITLE
Can't autoplay next song when playing playlist

### ISSUE THREAD

**Issue by mxckaito** [KRTirtho/spotube#113]
**Describe the bug**
Can't play the next song when playing a playlist

**Installation Source/Method**
- Package Manager: Flatpak

**Desktop (please complete the following information):**
 - OS: Parrot OS
 - Version [v2.0.0]

**Comment by KRTirtho** [comment]
Just upgrade to latest version (v2.2.1). This problem has been fixed

**Comment by koboingangkang** [comment]
still persist in v2.2.1
method of installation : 
1. fdroid
2. apk

**Comment by KRTirtho** [comment]
It's been fixed from v2.3.0

**Comment by Playit3110** [comment]
Still, doesn't work on v3.5.0. Maybe clip a bit on the end to have a time that is earlier than the end.

Like a Song with 3:12 min length, take instead 3:10 min as the end of the song and continue with the next one. Maybe even preload the next song, so if something goes wrong you can skip the next song and jump to the third.
