### ISSUE TITLE
Alternative track source does not persist after closing the app.

### ISSUE THREAD

**Issue by HeyItsFiore** [KRTirtho/spotube#1223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Although the patch notes said it should be fixed, when I select a new alternative track source and close the app, it goes back to the original selection ignoring my choice.

### Expected Behavior

After selecting a new alternative track source, it should be mantained even after closing the app and not reset to the original choice.

### Steps to reproduce

1. Opened Spotube
2. Started a song, wrong track
3. Selected the new track
4. Closed Spotube
5. Reopened Spotube, song was back on the wrong track

### Operating System

Windows 11

### Spotube version

v3.4.1 (latest)

### Installation source

GitHub Releases (Binary)

### Additional information

This is especially strange since I managed to keep only one song with an alternative track source, but any other just revert back. I did try uninstalling and reinstalling, no changes. This is technically a duplicate of #840, but it's not resolved for me.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment]
Can you specify what song(s) it's happening with? Because I was unable to reproduce this issue.

As long as you've not changed the audio source ("Settings" > "Audio Source") before playing that particular song once again, it should remember the manually selected match

**Comment by crbenne** [comment]
I'm also having the same issue -- this is the song https://open.spotify.com/track/57gvyHE7smXf3gaRH794lt

Something quite odd, at first it plays an episode from the Critical Role podcast. If I look at the alternative sources, there are none unless I click the magnifying glass and change the search from "lievery voice - main vox mix - Jasper Street Co., Mousse T." to "lift every voice - main vox mix - Jasper Street Co., Mousse T." (for some reason the "ft" is missing from the original search.

When I choose the alternative track, it will remember the selection until I close and reopen Spotube, then it goes back to the original result

**Comment by KRTirtho** [comment]
Looks like the regex that cleans the track title is removing the `ft ` from `lift` thus it's `lievery song -....`

**Comment by KRTirtho** [comment]
This line is the culprit

https://github.com/KRTirtho/spotube/blob/5d0b5e69a5e43b17561656160fd963de4ff0f833/lib/utils/service_utils.dart#L57

**Comment by KRTirtho** [comment]
@crbenne Fixed in 86123456f2ff577921cf62cffca180427dfe1dd5

But your actual issue was related to #883 not this one

**Comment by HeyItsFiore** [comment]
> Can you specify what song(s) it's happening with? Because I was unable to reproduce this issue.
> 
> As long as you've not changed the audio source ("Settings" > "Audio Source") before playing that particular song once again, it should remember the manually selected match

Sorry for the late reply! Basically, any of them; I'm testing right now with https://open.spotify.com/track/46scODShYFATHbLfLE0dr1 (it finds the Midnight version) or https://open.spotify.com/track/6rdkCkjk6D12xRpdMXy0I2 (completely wrong song).
If I select them manually after failing the first time, it is mantained. But if I close and open the app again, the choice is forgotten and I have to select again which songs are the right ones. I am not changing the audio source between uses of the app, by the way. Thank you for your help!

**Comment by KRTirtho** [comment]
This has been fixed in #1687

**Comment by DqrknessItself** [comment]
I'm still having this issue with more than one song :)
This might be due to the fact that they have japanese names.
However, the exact correct version appears as the second source.
I can't see if or how I can create a preference for or download a source so please let me know if I have anything wrong!

https://song.link/s/3rCJptQKkXrTx6qUXqz7dD
https://song.link/s/3rCJptQKkXrTx6qUXqz7dD
https://song.link/s/5sPKAEb7afrIMtdqEnI6H6

**Comment by Francisco1asir** [comment]
It seems like in the version 3.8.0 in android, the bug is solvented, I still have to do more tests, thanks!!
