### ISSUE TITLE
Skipping songs, not playing musoc

### ISSUE THREAD

**Issue by Hoosck** [KRTirtho/spotube#1584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Tries to play a song and skips several songs on a list until one is played

### Expected Behavior

Play a song, anthen proceed to play the next one on a list

### Steps to reproduce

1. I opened the app. 
2. Authentication error displays.
4. Close & re open the app several times until everithing loads ok without error message
5. Try to play a song.

### Operating System

Android v14

### Spotube version

3.71

### Installation source

Play Store (Android)

### Additional information

Its a wonderfull app, i hope this get solved

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Annie-G** [comment]
Can confirm, some songs in my playlists are now being skipped. I believe it was not like that before the last update.

**Comment by KRTirtho** [comment]
Try in 3.8.0. This issue has been fixed

**Comment by Kumicoo** [comment]
> Try in 3.8.0. This issue has been fixed

No, it hasn't. Stop Capping. It is still happening. It is happening to me RIGHT NOW. Fix your shit.
