### ISSUE TITLE
[bug] Spotify Login not working on Fedora 40 (Flatpak)

### ISSUE THREAD

**Issue by universish** [KRTirtho/spotube#1930]
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

In Fedora 40 XFCE desktop environment, in Gnome desktop environment, in KDE desktop environment; wayland or x11 when I click on the login with spotify account button, the spotify login link opens in some unknown web browser-like thing, but no image appears. I cannot log in because the webpage does not open.

### Expected Behavior

Request to be able to log in with Spotify account.

### Steps to reproduce

1. Settings
2. Sign in with your Spotify account.

### Logs

macellan@fedora:~$ flatpak run com.github.KRTirtho.Spotube
Gtk-Message: 16:29:18.043: Failed to load module "xapp-gtk3-module"
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
flutter: Error loading artUri: Invalid argument(s): No host specified in URI /tmp/spotube/An%20Eisai%20Ena%20Asteri%20-%20Nikos%20Vertis.jpg
#0      _HttpClient._openUrl (dart:_http/http_impl.dart:2749)
#1      _HttpClient.openUrl (dart:_http/http_impl.dart:2620)
#2      IOClient.send (package:http/src/io_client.dart:117)
#3      HttpFileService.get (package:flutter_cache_manager/src/web/file_service.dart:37)
#4      WebHelper._download (package:flutter_cache_manager/src/web/web_helper.dart:115)
#5      WebHelper._updateFile (package:flutter_cache_manager/src/web/web_helper.dart:97)
<asynchronous suspension>
#6      WebHelper._downloadOrAddToQueue (package:flutter_cache_manager/src/web/web_helper.dart:65)
<asynchronous suspension>

** (spotube:2): CRITICAL **: 16:29:24.681: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (spotube:2): CRITICAL **: 16:29:24.682: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (spotube:2): CRITICAL **: 16:29:24.682: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (spotube:2): CRITICAL **: 16:29:24.682: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (spotube:2): CRITICAL **: 16:29:24.682: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(spotube:2): GLib-GObject-CRITICAL **: 16:29:24.682: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (spotube:2): CRITICAL **: 16:29:24.682: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:2): CRITICAL **: 16:29:24.841: void fl_engine_send_window_metrics_event(FlEngine *, size_t, size_t, double): assertion 'FL_IS_ENGINE(self)' failed
Gtk-Message: 16:29:25.080: Failed to load module "xapp-gtk3-module"

** (spotube:2): CRITICAL **: 16:29:25.722: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed
Failed to create GBM buffer of size 1280x680: Geçersiz argüman

** (spotube:2): CRITICAL **: 16:29:25.746: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:2): CRITICAL **: 16:29:25.746: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:2): CRITICAL **: 16:29:25.893: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:2): CRITICAL **: 16:29:26.649: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:2): CRITICAL **: 16:29:26.955: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:2): CRITICAL **: 16:29:26.973: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:2): CRITICAL **: 16:29:26.973: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:2): CRITICAL **: 16:29:27.399: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed
~WebviewWindow

(spotube:2): GLib-GObject-CRITICAL **: 16:29:35.544: ../gobject/gsignal.c:2685: instance '0x5ba760bd1b0' has no handler with id '391'

### Operating System

fedora 40

### Spotube version

v3.8.1 stable

### Installation source

GitHub Releases (Binary)

### Additional information

Installation source: flathub
https://flathub.org/apps/com.github.KRTirtho.Spotube

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by notwithering** [comment]
i have the same issue
![image](https://github.com/user-attachments/assets/b2aa3dde-48db-49cb-a92a-8ee0c051005f)

<details>
<summary>logs:</summary>

the logs output from the logs button in settings always cuts off my log, this is most likely a useless log output which is why i made it collapsible, if there is a log FILE i dont know about someone please tell me so i can provide a useful log output. this is all i have:

```
/src/widgets/framework.dart:5203)
#330    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#331    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#332    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#333    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#334    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#335    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)
#336    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#337    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#338    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#339    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#340    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#341    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#342    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#343    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#344    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#345    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#346    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)
#347    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#348    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#349    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#350    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#351    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#352    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#353    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#354    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#355    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#356    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#357    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#358    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#359    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#360    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#361    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#362    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#363    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#364    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#365    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)
#366    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#367    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#368    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#369    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#370    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#371    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#372    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#373    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#374    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#375    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#376    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)
#377    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#378    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#379    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#380    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#381    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#382    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#383    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#384    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#385    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#386    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#387    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#388    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#389    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#390    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#391    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#392    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#393    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#394    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#395    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#396    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#397    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#398    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#399    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#400    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#401    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#402    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#403    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#404    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#405    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#406    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#407    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#408    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#409    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#410    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#411    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#412    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#413    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#414    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#415    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#416    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#417    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)
#418    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#419    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#420    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#421    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#422    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#423    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#424    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#425    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#426    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)
#427    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#428    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#429    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#430    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#431    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#432    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#433    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#434    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#435    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#436    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#437    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#438    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#439    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#440    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#441    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#442    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#443    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#444    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#445    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#446    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#447    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#448    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#449    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#450    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#451    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#452    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#453    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#454    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#455    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#456    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#457    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#458    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#459    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#460    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#461    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#462    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#463    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#464    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#465    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#466    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#467    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#468    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#469    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)
#470    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#471    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#472    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#473    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#474    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#475    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#476    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#477    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#478    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#479    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#480    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#481    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#482    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#483    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#484    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#485    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#486    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#487    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#488    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#489    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#490    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#491    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#492    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#493    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#494    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#495    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#496    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#497    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#498    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#499    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#500    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#501    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#502    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#503    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#504    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#505    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#506    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#507    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#508    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)
#509    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#510    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#511    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#512    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#513    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#514    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#515    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#516    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#517    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#518    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#519    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#520    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#521    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#522    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#523    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#524    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#525    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#526    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#527    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#528    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#529    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#530    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#531    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#532    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#533    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#534    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#535    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#536    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#537    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#538    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6904)
#539    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6916)
#540    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#541    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#542    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#543    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#544    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#545    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#546    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#547    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#548    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#549    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#550    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#551    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#552    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#553    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#554    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#555    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#556    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#557    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#558    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#559    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#560    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#561    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#562    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#563    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#564    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#565    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#566    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#567    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#568    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#569    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#570    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#571    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#572    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#573    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#574    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#575    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#576    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#577    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#578    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#579    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#580    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#581    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#582    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#583    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#584    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#585    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#586    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#587    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#588    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#589    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#590    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#591    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#592    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)
#593    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#594    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#595    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6769)
#596    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#597    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#598    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#599    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#600    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#601    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#602    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#603    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#604    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#605    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#606    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#607    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#608    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#609    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#610    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#611    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#612    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#613    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#614    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#615    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#616    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#617    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#618    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#619    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#620    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#621    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#622    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#623    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#624    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#625    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#626    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#627    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#628    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#629    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#630    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#631    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#632    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#633    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#634    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#635    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#636    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#637    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#638    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#639    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#640    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#641    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#642    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#643    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6904)
#644    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6916)
#645    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#646    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#647    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#648    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#649    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#650    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#651    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5641)
#652    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#653    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#654    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#655    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#656    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#657    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#658    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#659    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#660    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#661    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#662    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#663    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5469)
#664    ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463)
#665    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340)
#666    Element.updateChild (package:flutter/src/widgets/framework.dart:3849)
#667    _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:155)
#668    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2845)
#669    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:173)
#670    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2688)
#671    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1097)
#672    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2688)
#673    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:248)
#674    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:331)
#675    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#676    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173)
#677    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1097)
#678    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237)
#679    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404)
#680    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#681    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#682    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#683    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#684    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1426)
#685    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#686    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#687    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#688    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#689    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#690    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#691    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#692    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#693    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#694    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#695    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#696    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#697    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#698    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#699    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#700    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#701    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#702    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#703    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#704    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#705    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3712)
#706    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#707    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#708    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#709    _RenderTheaterMixin.layoutChild (package:flutter/src/widgets/overlay.dart:974)
#710    _RenderTheater.performLayout (package:flutter/src/widgets/overlay.dart:1288)
#711    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#712    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#713    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#714    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#715    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#716    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
#717    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:574)
#718    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:601)
#719    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#720    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#721    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#722    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#723    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#724    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#725    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#726    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#727    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#728    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#729    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#730    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
#731    RenderObject.layout (package:flutter/src/rendering/object.dart:2577)
#732    RenderView.performLayout (package:flutter/src/rendering/view.dart:244)
#733    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2416)
#734    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051)
#735    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064)
#736    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:577)
#737    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1138)
#738    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443)
#739    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392)
#740    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313)
#741    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171)
#742    _rootRun (dart:async/zone.dart:1399)
#743    _CustomZone.run (dart:async/zone.dart:1301)
#744    _CustomZone.runGuarded (dart:async/zone.dart:1209)
#745    _invoke (dart:ui/hooks.dart:314)
#746    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#747    _drawFrame (dart:ui/hooks.dart:283)

----------------------------------------
[2024-09-30 15:10:50.982763]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      CustomSpotifyEndpoints.getFriendActivity (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:113)
<asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-09-30 15:10:51.276067]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1380)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1247)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:912)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#10     FeaturedPlaylistsNotifier.fetch (package:spotube/provider/spotify/playlist/featured.dart:33)
<asynchronous suspension>
#11     FeaturedPlaylistsNotifier.build (package:spotube/provider/spotify/playlist/featured.dart:44)
<asynchronous suspension>
#12     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-09-30 15:10:51.277339]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1380)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1247)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:912)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#10     SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------
--------------------
[2024-09-30 15:10:51.278537]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1380)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1247)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:912)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#10     AlbumReleasesNotifier.fetch (package:spotube/provider/spotify/album/releases.dart:35)
<asynchronous suspension>
#11     AlbumReleasesNotifier.build (package:spotube/provider/spotify/album/releases.dart:50)
<asynchronous suspension>
#12     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-09-30 15:10:51.296643]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1380)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1247)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:912)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      CursorPages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:292)
<asynchronous suspension>
#10     SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------
[2024-09-30 15:17:06.273704]---------------------
FormatException: Unexpected character (at character 1)
Too many requests
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1380)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1247)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:912)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35)
#4      JsonDecoder.convert (dart:convert/json.dart:610)
#5      JsonCodec.decode (dart:convert/json.dart:216)
#6      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:276)
#7      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#8      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#9      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#10     FavoritePlaylistsNotifier.fetch (package:spotube/provider/spotify/playlist/favorite.dart:33)
<asynchronous suspension>
#11     FavoritePlaylistsNotifier.build (package:spotube/provider/spotify/playlist/favorite.dart:44)
<asynchronous suspension>
#12     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-09-30 15:17:35.554202]---------------------
No track currently
#0      SyncedLyricsNotifier.build (package:spotube/provider/spotify/lyrics/synced.dart:131)
<asynchronous suspension>
#1      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
```

</details>

**Comment by KRTirtho** [comment]
Is spotify.com accessible in your browser?

**Comment by frangonf** [comment]
Same issue with Ubuntu 24.04 Gnome 46, with x86_64.deb and from 3.8.0 and up.

Login screen is "covered" by blank screen. Spotify login rendering behind, semi visible after messing around clicking and dragging.

Same result with different browsers (firefox, librefox, chrome, edge) as default system browser.

<img width="993" alt="image" src="https://github.com/user-attachments/assets/9488806d-a05b-413e-88e1-da79c0410c27">

<img width="870" alt="image" src="https://github.com/user-attachments/assets/fe967e3d-2dfa-4e75-9cba-bb91ae652ce8">


```
╚ $ spotube
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.

** (spotube:1952671): CRITICAL **: 20:51:27.992: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (spotube:1952671): CRITICAL **: 20:51:27.992: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (spotube:1952671): CRITICAL **: 20:51:27.992: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (spotube:1952671): CRITICAL **: 20:51:27.992: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (spotube:1952671): CRITICAL **: 20:51:27.992: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(spotube:1952671): GLib-GObject-CRITICAL **: 20:51:27.992: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (spotube:1952671): CRITICAL **: 20:51:27.992: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:1952671): CRITICAL **: 20:51:28.080: void fl_engine_send_window_metrics_event(FlEngine *, size_t, size_t, double): assertion 'FL_IS_ENGINE(self)' failed
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

** (spotube:1952671): CRITICAL **: 20:51:29.427: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:1952671): CRITICAL **: 20:51:29.436: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:1952671): CRITICAL **: 20:51:29.436: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:1952671): CRITICAL **: 20:51:30.169: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:1952671): CRITICAL **: 20:51:30.421: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:1952671): CRITICAL **: 20:51:30.421: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:1952671): CRITICAL **: 20:51:30.473: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

** (spotube:1952671): CRITICAL **: 20:51:31.996: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (spotube:1952671): CRITICAL **: 20:51:31.996: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed
AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer
```

**Comment by notwithering** [comment]
in case anyone with this issue needed help on how to still log in without being able to see the page, ive created a bit of "tutorial"

https://github.com/user-attachments/assets/18114d59-9e28-44b4-840f-972436b8c289

**Comment by KRTirtho** [comment]
@notwithering that's one cursed way to login 💀 

But I'm guessing, it's something with the Window Manager.

**Comment by KRTirtho** [comment]
Btw, if you installed with `dpkg`, please uninstall it as it won't install the required dependencies with the .deb package
Use `apt install ./path/to/spotube.deb` instead

**Comment by notwithering** [comment]
> Btw, if you installed with `dpkg`, please uninstall it as it won't install the required dependencies with the .deb package Use `apt install ./path/to/spotube.deb` instead

the two AUR packages for spotube also seem to have difference dependencies

- spotube-bin (pkgver=3.8.2): 
`depends=('mpv' 'libappindicator-gtk3' 'libsecret' 'jsoncpp' 'libnotify' 'xdg-user-dirs' 'webkit2gtk-4.1')`
- spotube (pkgver=3.8.2):
`depends=("gcc-libs" "mpv" "libappindicator-gtk3" "libsecret" "libnotify" "webkit2gtk-4.1" "libsoup3" "libayatana-appindicator")`

although this doesnt seem to be the problem for the login as i have all the packages that spotube depends on installed but if someone doesnt already have them it could cause a problem

**Comment by KRTirtho** [comment]
`spotube-bin` is officially maintained. So be aware of it.
`spotube` in aur isn't malicious but still be careful as it's after all aur. And anything can be there

**Comment by notwithering** [comment]
> `spotube-bin` is officially maintained. So be aware of it.
> `spotube` in aur isn't malicious but still be careful as it's after all aur. And anything can be there

I always check the PKGBUILD so I can be sure it's safe. Thanks for the heads up though. 😄

**Comment by Acosta01-dev** [comment]
> in case anyone with this issue needed help on how to still log in without being able to see the page, ive created a bit of "tutorial"
> 2024-10-02.18-09-41.mp4

thank you

**Comment by Alastair-L** [comment]
If it helps, I have the same issue with 
- Linux mint 22
- Flatpack 3.8.3
- KDE Plasma (x11)

**Comment by benmordecai** [comment]
Same issue with Arch KDE and flatpak on Wayland

**Comment by benmordecai** [comment]
![image](https://github.com/user-attachments/assets/6543f670-c56a-4fa8-b815-db888d82addc)

**Comment by benmordecai** [comment]
I am guessing that it is using some kind of Gnome platform embedded browser so as a test I installed Gnome Web and it also has some weird zoom issue. 
![image](https://github.com/user-attachments/assets/3ccd706f-2c15-4176-9761-779eaaa64304)

There is some kind of error where the zoom is NaN
![image](https://github.com/user-attachments/assets/9c61d58d-4331-4abf-af9a-c6cc21b504bb)

**Comment by universish** [comment]
Spotube flathub's flatpak new version does not have this problem. It has been fixed.  It has been fixed. 

Since the thread is about fedora 40 and the bug in the flatpak version, I'm closing it. Please create a new issue for a different platform with the name of that platform. Sincerely.

**Comment by NaterEST** [comment]
Not fixed on `spotube-bin` it seems. Using Thorium Browser as default (based on Chromium) on X11 (Xorg). Logged in with the same cursed procedure as notwithering did.
