### ISSUE TITLE
[Bug] Android - F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [KRTirtho/spotube#430]
Saw version 17 fail: https://gitlab.com/fdroid/fdroiddata/-/jobs/3891617399

So I tried to bump Flutter to 3.7.6, but that brought up `librust.so` binary deps to the surface: https://gitlab.com/fdroid/fdroiddata/-/commit/493af32591b1b93607b30f9557a2e0c6b3a755b5#note_1305278538

OK, so I built that too: https://gitlab.com/fdroid/fdroiddata/-/commit/1e3e91193e2a6c7003a351fe1499a84bd6a37d0f

But still fails later in Flutter: 
[oss.krtirtho.spotube_17.log.gz](https://github.com/KRTirtho/spotube/files/10921102/oss.krtirtho.spotube_17.log.gz)

**Comment by KRTirtho** [comment]
librust.so is a required dependency. It parses and writes metadata for mp3/m4a/ogg/floc etc audio formats
Removing it from the build will definitely cause error

**Comment by KRTirtho** [comment]
Also not sure about rebuilding in the pipeline. Is it a good idea?

**Comment by licaon-kter** [comment]
As said, we rebuild it...

What's next?

**Comment by KRTirtho** [comment]
> Also the error above is at build time, not while running the app... we did not reach that step yet. :)

yeah right

> What's next? Which Flutter version did you use?
v3.7.3

**Comment by KRTirtho** [comment]
Also, the pipeline using Java 8 right?

**Comment by KRTirtho** [comment]
Oh... Ok. In 2.7.0 I added a .env file which is required

**Comment by KRTirtho** [comment]
@licaon-kter is there any way to provide the content of the .env file without exposing them?

**Comment by licaon-kter** [comment]
> is there any way to provide the content of the .env file without exposing them?

No... we have no secrets... your recipe already provides some: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/oss.krtirtho.spotube.yml#L212-L213 are those not enough?


> Btw, this workflow might help you https://github.com/KRTirtho/metadata_god/blob/v0.3.2/.github/workflows/build-libs.yaml
>  the pipeline using Java 8 right?

Yeah, saw it, but I kinda ignored Java 8 :)
Since last year we switched to Debian Bullseye so it's Java11 by default.
But I can have it use Java8 if needed.

Well... once you clarify what `.env` should contain.

**Comment by KRTirtho** [comment]
Luckily, the app can run without the backend. So the basic info will get the job done. Let's do this workaround for this release, in the next one I'll use a better way of connecting to backend

So create the .env in project root
```bash
$ echo "POCKETBASE_URL=https://spotube.pockethost.io/" >> .env
```

**Comment by licaon-kter** [comment]
Taking it for a spin now

**Comment by licaon-kter** [comment]
Can you test the APK? (remove the `.zip` and unpack with .001 with 7zip)
[st.7z.001.zip](https://github.com/KRTirtho/spotube/files/10929090/st.7z.001.zip)
[st.7z.002.zip](https://github.com/KRTirtho/spotube/files/10929091/st.7z.002.zip)
[st.7z.003.zip](https://github.com/KRTirtho/spotube/files/10929094/st.7z.003.zip)
[st.7z.004.zip](https://github.com/KRTirtho/spotube/files/10929095/st.7z.004.zip)


Another thing, it does not make sense to check for updates for the F-Droid build, so, is it enough to set this to `false` at build time? https://github.com/KRTirtho/spotube/blob/v2.7.0/lib/provider/user_preferences_provider.dart#L51

**Comment by KRTirtho** [comment]
Cannot open archive. 7z not working

```
$ 7za e st.7z.001
7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (306A9),ASM)

Scanning the drive for archives:
         
ERROR: No more files
st.7z.001

System ERROR:
Unknown error -2147024872
```

**Comment by licaon-kter** [comment]
The archive files work fine for me, delete them and redownload :shrug:

**Comment by KRTirtho** [comment]
Can you provide me this with a zip format. I don't know why these are not working. Other 7z files working fine

**Comment by licaon-kter** [comment]
ZIP can't do multivolumes and the upload size is limited here :shrug:

**Comment by KRTirtho** [comment]
> And the answer is ... no... as that makes it ... fail to build scream

No it should build, this means by default the update checker will be toggled off

**Comment by KRTirtho** [comment]
And I can confirm everything is still working as expected

**Comment by licaon-kter** [comment]
I've retried now and it build fine :facepalm: nvm me then

Anyway, that line works fine, check update is disabled and the app does not start to connect to Github right away.

So, can we update the recipe to include this?

**Comment by KRTirtho** [comment]
Yup

**Comment by licaon-kter** [comment]
Done, thanks https://gitlab.com/fdroid/fdroiddata/-/commit/b0fec80aa3bd4e0e38d1b5e742d3a7b05f4d194a

**Comment by KRTirtho** [comment]
Just using `.gitmodules`?

**Comment by KRTirtho** [comment]
But I already have a [fvm](https://fvm.app/) configuration in the `.fvm` which is a natural way of handling flutter versions
Can f-droid use fvm automatically when it detects the `.fvm/flutterSdkVersion` file?

**Comment by licaon-kter** [comment]
This is news to me, is this a new thing or? I don't recall Flutter devs using this so far... we're mostly guessing the version and "hope latest works" :)

**Comment by KRTirtho** [comment]
fvm has been around for a while now😄

**Comment by licaon-kter** [comment]
I guess that most projects that are in F-Droid might not use it then

**Comment by KRTirtho** [comment]
You can always make it a requirement for flutter apps. It's better to keep track of Flutter versions for your app then failing on CI

**Comment by KRTirtho** [comment]
@licaon-kter Spotube 2.7.0 is still not available in the fdroid repo. Was there any problem building it?

**Comment by licaon-kter** [comment]
Cycle still ongoing: https://monitor.f-droid.org/builds/running

**Comment by licaon-kter** [comment]
ref: https://monitor.f-droid.org/builds/log/oss.krtirtho.spotube/18#site-footer

ref: https://github.com/KRTirtho/metadata_god/issues/9

**Comment by KRTirtho** [comment]
I'll make an MR with the fix

**Comment by licaon-kter** [comment]
It was more than this: https://gitlab.com/fdroid/fdroiddata/-/commit/c7e38b623e8dad0b1a521b716bfeaf4e4d70bd6e ? :)

Builds fine

**Comment by KRTirtho** [comment]
Man I fixed it already but forgot to create an MR 😂 All 3 hours in vain 🥲
Great work btw! Sorry for all the trouble ❤️

**Comment by licaon-kter** [comment]
Recipe needs an update

So fails with: https://gitlab.com/fdroid/fdroiddata/-/jobs/4580191732#L779

Looks like maybe you forgot to bump flutter version? https://github.com/KRTirtho/spotube/blob/v3.0.0/.fvm/fvm_config.json#L2

Let me set it to 3.10.5 (latest stable) locally
```
Error when reading 'bin/create-secrets.dart': No such file or directory.
```
Oh... https://github.com/KRTirtho/spotube/tree/v3.0.0/bin

What now?

**Comment by KRTirtho** [comment]
I'll update it and create a MR

**Comment by KRTirtho** [comment]
Closing as it is resolved now

It can be re-opened if same issue is face again

**Comment by linsui** [comment]
We need the lastFmApiKey for 3.2.0. Could you please update the metadata? Thanks!

**Comment by KRTirtho** [comment]
Yea sure sure. Why do I always forget about F-Droid! :facepalm:

**Comment by KRTirtho** [comment]
Please check https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13873
