### ISSUE TITLE
Does not remember changed track source

### ISSUE THREAD

**Issue by forteller** [KRTirtho/spotube#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When for example a live version of a song plays and your change the track source to the correct version, next time you open the app and plays the same song, it goes back to the wrong version.

### Expected Behavior

Spotube should have a global database of the correct YT video for each track that has ever been changed by anyone. If more than for example 5 people have changed the same track to the same video, then the default video used when people play that track should be changed.

Or at least the local Spotube should remember your local changes. But the first option would be much better.

### Steps to reproduce

1. Open app, play a track
2. Use the Alternative Tracks Sources tool to switch the source
3. Close app
4. Reopen app
5. Play the same track again, notice that it's back to the previous, wrong source.

### Operating System

Linux

### Spotube version

2.7.0

### Installation source

Flathub (Flatpak)

### Additional information

Thank you for your great work!

**Comment by RaptaG** [comment]
I can reproduce

**Comment by KRTirtho** [comment]
Hmm, it only happens when "Pre-download and Play" is on. Maybe even after changing the source, the old cached (downloaded) track doesn't get refreshed

**Comment by djnizzi** [comment]
Also if I change the source, it still downloads the source that it has assigned before I changed it

**Comment by forteller** [comment]
Nuclear has now implemented a system like this. Maybe you could work together to make a common library of correct songs/videos, that anyone could connect to? That would be amazing. https://nukeop.gitbook.io/nuclear/user-manual/stream-verification

**Comment by RaptaG** [comment]
Fixed in 3.0.0

**Comment by KajzerD** [comment]
This problem is still happening in 3.0.0 version. I'm on Windows 10, after I manually change the song with "Alternative Track Source" it works fine as long as the program is open. If I restart the program or clear my song queue, it completely forgets the track I set and it defaults to the wrong one. I even tried running the program with Admin privilegies and it still happens.

**Comment by RaptaG** [comment]
@KRTirtho
