### ISSUE TITLE
It's not runnig on debian 12

### ISSUE THREAD

**Issue by geekmrx** [KRTirtho/spotube#552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

-

### Expected Behavior

-

### Steps to reproduce

Depende: gir1.2-appindicator3-0.1 but not is installable

### Operating System

Debian 12

### Spotube version

v3.0.0

### Installation source

GitHub Releases (Binary)

### Additional information

v3.0.0 Spotube-linux-x86_64.deb

**Comment by RaptaG** [comment]
Please fill out all the missing fields, otherwise we cannot help you

**Comment by RaptaG** [comment]
And also log output would be helpful

**Comment by Rumplown** [comment]
You need to download the AppImage, the deb you downloaded is for ubuntu.

1.  Download AppImage from [here](https://github.com/KRTirtho/spotube/releases/latest/download/Spotube-linux-x86_64.AppImage)
2. Install libmpv-dev
`sudo apt install libmpv-deb`
3. make the AppImage executable
`chmod +x ./Spotube-linux-x86_64.AppImage`
4. Run it
`./Spotube-linux-x86_64.AppImage`
5. Enjoy 🎉

If you want to create an icon and register it in the app library you can create a .desktop file with icon and binary. This kind of [guide](https://trendoceans.com/create-a-desktop-icon-for-an-appimage-application/) can help you.

**Comment by kuadrat** [comment]
I had encountered the same issue when trying to install the `.deb` file on Debian 12 (bookworm).

It turns out that the underlying cause is that Debian 12 has moved from appindicator to ayatana-appindicator (as described here: https://github.com/AyatanaIndicators/libayatana-appindicator/issues/30).

Given that Ubuntu is planning to follow Debian in deprecating appindicator in favour of ayatana-appindicator (see https://bugs.launchpad.net/ubuntu/+source/libayatana-appindicator/+bug/1915695), it might make sense for Spotube to anticipate and move to libayatana-appindicator already.

<sub>P.S. Let me use this opportunity to thank all contributors for working on such a great app!</sub>

**Comment by KRTirtho** [comment]
It has been fixed on Nightly

**Comment by KRTirtho** [comment]
Fixed in v3.1.1

**Comment by PhilDevProg** [comment]
The libayatana-appindicators issues still happens on Debian Trixie (13) while building via flatpak-builder.

**Comment by KRTirtho** [comment]
Why'd u build the flatpak instead of installing?

**Comment by PhilDevProg** [comment]
Because there currently is no arm Flatpak

**Comment by KRTirtho** [comment]
This is not happening because of this, for sure. It happens only to the `.deb` package. In flatpak Spotube is using distro agnostic dependencies so no way this can cause an issue

**Comment by PhilDevProg** [comment]
I tried building it via `flatpak-builder --user --install --force-clean build com.github.KRTirtho.Spotube.yml` but I always get this error so I thougt it may have something to do with this issue:

```
(flatpak-builder:496407): flatpak-builder-ERROR **: 19:31:43.526: Failed to load included manifest (/home/droidian/com.github.KRTirtho.Spotube/shared-modules/libappindicator/libappindicator-gtk3-12.10.json): Failed to open file ?/home/droidian/com.github.KRTirtho.Spotube/shared-modules/libappindicator/libappindicator-gtk3-12.10.json?: No such file or directory
```

**Comment by KRTirtho** [comment]
How did you clone the repo? The repo has submodules, so you've to clone them as well

```bash
$ git clone https://github.com/KRTirtho/com.github.KRTirtho.Spotube --recursive --shallow-submodules --depth=1 --single-branch
```

**Comment by PhilDevProg** [comment]
Yes! That was indeed the problem. Thanks!
