### ISSUE TITLE
spotub doesn't exit properly, hangs in infinite loop

### ISSUE THREAD

**Issue by hamkg** [KRTirtho/spotube#768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting from terminal I get the message
`flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.`
libmedia_kit_native_event_loop.so is part of the package and duly installed.

When trying to exit a loop goes on ad infinitum:
```
Attempt:11 waiting for isolate vm-isolate to check in
Attempt:11 waiting for isolate InitializerIsolate._mainloop to check in
Attempt:12 waiting for isolate vm-isolate to check in
Attempt:12 waiting for isolate InitializerIsolate._mainloop to check in
```
I have to end the program with killall (or via system monitor).

### Expected Behavior

No warning at startup, normal shutdown when exiting

### Steps to reproduce

As described above under "Current behaviour"

### Operating System

Linux

### Spotube version

3.1.2 rpm package

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by dimitris-personal** [comment]
Same here with flatpak from flathub, Fedora 38/GNOME/Wayland.

**Comment by hamkg** [comment]
OK, I've realised what lies behind this. ldd /usr/bin/spotube reveals the following:
`	libcatcher_plugin.so => not found
	libfile_selector_linux_plugin.so => not found
	libflutter_secure_storage_linux_plugin.so => not found
	liblocal_notifier_plugin.so => not found
	libmedia_kit_libs_linux_plugin.so => not found
	libscreen_retriever_plugin.so => not found
	libsystem_theme_plugin.so => not found
	libsystem_tray_plugin.so => not found
	liburl_launcher_linux_plugin.so => not found
	libwindow_manager_plugin.so => not found
	libwindow_size_plugin.so => not found
	libflutter_linux_gtk.so => not found
`
All these files are located in /usr/share/spotube/lib/ but system looks for them in /usr/lib64. After creating symlinks , everything works properly.

**Comment by hamkg** [comment]
Didn't test long enough - turned out that the symlinks didn't help. There was a difference, though: the program seemed to shutdown (window closed), but the process was still running in the background. Back to square one :(

**Comment by hamkg** [comment]
As mentioned above, ldd /usr/bin/spotube reveales 12 missing .so libraries. However, 3 of the libraries in /usr/share/spotube/lib/ are not reported missing:
libapp.so
libmedia_kit_native_event_loop.so
libmetadata.god.so

I have no knowledge of flutter/dart but googling suggests that the libmedia_kit_native_event_loop.so might be related to this issue - plus that I get a warning that it can't be found. A symlink from /usr/share/spotube/lib/ to /usr/lib64 does not help. To me it seems as if spotube's call to this library goes wrong somehow.

A comment from the devs would be most appreciated.

**Comment by KRTirtho** [comment]
No `libmedia_kit_native_event_loop` isn't really related to this.

> OK, I've realised what lies behind this. ldd /usr/bin/spotube reveals the following: ` libcatcher_plugin.so => not found libfile_selector_linux_plugin.so => not found libflutter_secure_storage_linux_plugin.so => not found liblocal_notifier_plugin.so => not found libmedia_kit_libs_linux_plugin.so => not found libscreen_retriever_plugin.so => not found libsystem_theme_plugin.so => not found libsystem_tray_plugin.so => not found liburl_launcher_linux_plugin.so => not found libwindow_manager_plugin.so => not found libwindow_size_plugin.so => not found libflutter_linux_gtk.so => not found ` All these files are located in /usr/share/spotube/lib/ but system looks for them in /usr/lib64. After creating symlinks , everything works properly.

This is also not a reason ig because flutter executable (./spotube) dynamically loads those libs as far as I know

It's probably related to `window_manager`. The window close button calls the `windowManager.close()`  method which closes the window

**Comment by hamkg** [comment]
Thanks for the reply, KRTirtho!
You write:
`It's probably related to window_manager. The window close button calls the windowManager.close() method which closes the window`

OK, so is there a way to solve this and to get a proper exit behaviour?

I've tried both the MATE desktop (Marco WM) and XFCE (Xfwm), no difference.

**Comment by aleister888** [comment]
Well a temporary fix is to run Spotube from a script that logs the app output and closes it when this happens:

`#!/bin/sh

LOG_FILE=/tmp/spotube.log

echo "" > $LOG_FILE

while true; do
	grep "Attempt" $LOG_FILE && killall spotube
	sleep 0.25;
done &

(
/usr/bin/spotube
) 2>&1 | tee -a /tmp/spotube.log`

**Comment by hamkg** [comment]
Good idea, but no difference on my system. I still get the "Spotube is not responding" message, allowing me to "Force quit".
I can live with that, though.

**Comment by KRTirtho** [comment]
Use the nightly version. It's been fixed there.

**Comment by hamkg** [comment]
Thanks, KRTirtho! Upgraded to the nightly rpm version and yes, spotube now shuts down properly when I right-click the systray button and choose "Quit".

However, if I activate the system title bar, click the spotube icon in top left corner, and choose "Quit", it hangs just like before, taking me to the "Spotube is not responding" message and allowing me to "Force quit".

**Comment by KRTirtho** [comment]
Yeah that was expected as I can't override the callback for the native titlebars
